# Generated by Django 3.0.6 on 2020-05-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='メインコンテンツ')),
                ('article', models.CharField(max_length=50, verbose_name='記事')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=50, verbose_name='サブタイトル')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MainContent')),
            ],
        ),
    ]
